services:
  ms-users:
    build: ./ms-users
    container_name: ms-users
    ports:
      - "${PORT_USERS}:${PORT_USERS}"
    # Quitamos el depends_on de sanos-db
    environment:
      - SERVER_PORT=${PORT_USERS}
      # Apuntamos a la variable DB_HOST que será el endpoint de RDS
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - sanos-network

  ms-pets:
    build: ./ms-pets
    container_name: ms-pets
    ports:
      - "${PORT_PETS}:${PORT_PETS}"
    environment:
      - SERVER_PORT=${PORT_PETS}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - sanos-network

  bff:
    build: ./bff
    container_name: bff
    ports:
      - "8080:8080"
    depends_on:
      - ms-users
      - ms-pets
    environment:
      - SERVER_PORT=8080
      - USERS_SERVICE_URL=http://ms-users:${PORT_USERS}
      - PETS_SERVICE_URL=http://ms-pets:${PORT_PETS}
    networks:
      - sanos-network

networks:
  sanos-network:
    driver: bridge

# Borramos la sección de volumes: pgdata ya que RDS maneja su propio almacenamiento
