spring.application.name=ms-pets

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/sanos_y_salvos_local
spring.datasource.username=admin_sanos
spring.datasource.password=sanos_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

