spring.application.name=ms-pets
server.port=8082

# Usa las variables que definiste en el .env y el docker-compose
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Esto es vital para que reconozca los Enums como pet_status
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect