spring.application.name=ms-pets
# Puerto del servidor
server.port=${SERVER_PORT:8082}

# Configuración de la Base de Datos
# Si está en Docker, usará el host 'sanos-db'. Si está en local, usará 'localhost'.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petrescue_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

<<<<<<< Updated upstream
# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
=======
spring.jpa.hibernate.ddl-auto=validate
>>>>>>> Stashed changes
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect