spring.application.name=bff
server.port=8080

# URLs de Microservicios
ms.users.url=http://ms-users:8081
ms.pets.url=http://ms-pets:8082
# AGREGA ESTA LÍNEA:
ms.notification.url=http://ms-notification:8083

bff.cors.allowed-origins=http://localhost:3000,https://*.vercel.app