spring.application.name=bff
server.port=${SERVER_PORT:8080}

# URLs de Microservicios — inyectadas por docker-compose
ms.users.url=${MS_USERS_URL:http://localhost:8081}
ms.pets.url=${MS_PETS_URL:http://localhost:8082}
ms.notification.url=${MS_NOTIFICATION_URL:http://localhost:8083}
ms.sightings.url=${MS_SIGHTINGS_URL:http://localhost:8084}
ms.matching.url=${MS_MATCHING_URL:http://localhost:8085}

# CORS
bff.cors.allowed-origins=http://localhost:3000,https://sanosysalvos-five.vercel.app