spring.application.name=ms-users
# Usamos el 8081 para no chocar con el puerto 8080 de tu pgAdmin (petrescue-pg)
server.port=8081

# ConexiÃ³n a la DB de tu captura
spring.datasource.url=jdbc:postgresql://localhost:5432/sanos_y_salvos_local
spring.datasource.username=admin_sanos
spring.datasource.password=sanos_pass


# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Conexión firebase
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/sanos-y-salvos-git