spring.application.name=ms-users
# Usamos el 8081 para no chocar con el puerto 8080 de tu pgAdmin (petrescue-pg)
server.port=8081

# Conexión a la DB de tu captura
spring.datasource.url=jdbc:postgresql://localhost:5432/petrescue_db
spring.datasource.username=user_admin
spring.datasource.password=password123

# JPA Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect