spring.application.name=ms-users
# Puerto del servidor (8081 para usuarios)
server.port=${SERVER_PORT:8081}

# Configuración de la Base de Datos
# Prioriza la variable de entorno de Docker, si no existe usa localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petrescue_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password123}

# JPA / Hibernate Config
# Nota: Aquí mantenemos 'validate' como tenías originalmente
spring.jpa.hibernate.ddl-auto=${JPA_DDL:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect